### ISSUE TITLE
1주차 과제: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#1]
## 목표
자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

## 학습할 것
- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

## 마감 일시 (한국 시간 기준)
- 2023년 5월 25일 오후 10시

**Comment by euichaan** [comment]
1주차 과제입니다.
https://chan9.tistory.com/184

**Comment by binary-ho** [comment]
1주차 과제입니다.

[바이트 코드를 JVM에 싸서 드셔보세요](https://dwaejinho.tistory.com/entry/JVM)

**Comment by ChooSeoyeon** [comment]
1주차 과제입니다.
https://choo.oopy.io/387fdd1c-bb18-4500-99b4-b0e9c1924d79
