### ISSUE TITLE
10주차 과제: 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#10]
# 목표
자바의 멀티쓰레드 프로그래밍에 대해 학습하세요.

# 학습할 것 (필수)
- Thread 클래스와 Runnable 인터페이스
- 쓰레드의 상태
- 쓰레드의 우선순위
- Main 쓰레드
- 동기화
- 데드락
# 마감일시
2023년 8월 5일 토요일 20시

**Comment by euichaan** [comment]
https://humorous-bass-b9e.notion.site/1ec4d0f7de0c46fd8f79d8b9a3aa60a7?pvs=4

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/10.%20%EB%A9%80%ED%8B%B0%EC%93%B0%EB%A0%88%EB%93%9C%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.md

다 작성 하진 못했습니다..

**Comment by ssssujini99** [comment]
https://adhesive-honey-f62.notion.site/10-179e38fabd834776804f1443fb222e42?pvs=4

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-10
