### ISSUE TITLE
11주차 과제: Enum과 애노테이션 

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#11]
# 목표
자바의 열거형과 애노테이션에 대해 학습하세요.

# 학습할 것 (필수)
## Enum
- enum 정의하는 방법
- enum이 제공하는 메소드 (values()와 valueOf())
- java.lang.Enum
- EnumSet
## 애노테이션 
- 애노테이션 정의하는 방법
- @retention
- @target
- @documented
- 애노테이션 프로세서
# 마감일시

**Comment by euichaan** [comment]
https://humorous-bass-b9e.notion.site/Enum-02daa3ae5dbc4eca940c3cded574d10a?pvs=4

**Comment by ssssujini99** [comment]
https://adhesive-honey-f62.notion.site/11-Enum-3ea80ad9ce1e49ec8f643c58abbb588c?pvs=4
https://adhesive-honey-f62.notion.site/11-Annotation-5f802b1b476647ad867a21cf90599348?pvs=4

**Comment by binary-ho** [comment]
급한 일이 있어 과제 enum 밖에 못 했습니다. 벌금 지불하겠습니다. 죄송합니다.

https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/11.1%20Enum.md

**Comment by ChooSeoyeon** [comment]
https://silent-apparatus-578.notion.site/Enum-929b9d0e770b4d8d8b1ddaa234b3a5d2?pvs=4

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-11-2

@binary-ho 저는 어노테이션밖에 못했는데 합체하실래요?
