### ISSUE TITLE
12주차 과제: 제네릭

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#12]
# 목표
자바의 제네릭에 대해 학습하세요.

# 학습할 것 (필수)
- 제네릭 사용법
- 제네릭 주요 개념 (바운디드 타입, 와일드 카드)
- 제네릭 메소드 만들기
- Erasure

# 학습할 것(선택)
- [토비의 봄 TV 자바 Generic (1)](https://www.youtube.com/watch?v=ipT2XG1SHtQ&t=2436s)
- [토비의 봄 TV 자바 Generic (2)](https://www.youtube.com/watch?v=PQ58n0hk7DI&t=18s)
# 마감일시

**Comment by ssssujini99** [comment]
https://adhesive-honey-f62.notion.site/12-c797316162264c6a82a5c66cc7102b8d?pvs=4

**Comment by euichaan** [comment]
https://github.com/euichaan/TIL/blob/main/java/generic/generic.md

**Comment by ChooSeoyeon** [comment]
https://www.notion.so/929b9d0e770b4d8d8b1ddaa234b3a5d2?pvs=4

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-12-1
