### ISSUE TITLE
13주차 과제: I/O

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#13]
# 목표
자바의 Input과 Ontput에 대해 학습하세요.

# 학습할 것 (필수)
- 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
- InputStream과 OutputStream
- Byte와 Character 스트림
- 표준 스트림 (System.in, System.out, System.err)
- 파일 읽고 쓰기
# 마감일시
2023년 8월 31일 목요일, 오후 10시까지

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/13.%20java%20IO.md

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-13-1
https://uwoobeat.vercel.app/java-live-study-13-2
