### ISSUE TITLE
2주차 과제: 자바 데이터 타입, 변수 그리고 배열

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#2]
## 목표
자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.
## 학습할 것
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var
## 마감 일시 (한국 시간 기준)
2022년 6월 16일 오후 10시

**Comment by binary-ho** [comment]
https://dwaejinho.tistory.com/entry/2%EC%A3%BC%EC%B0%A8-%EC%9E%90%EB%A3%8C%ED%98%95

**Comment by euichaan** [comment]
https://chan9.tistory.com/186

**Comment by ChooSeoyeon** [comment]
https://choo.oopy.io/8a9bb495-929f-4174-b811-a8552bece499

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-02
