### ISSUE TITLE
3주차 과제: 연산자

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#3]
## 목표
자바가 제공하는 다양한 연산자를 학습하세요.
## 학습할 것
- 산술 연산자
- 비트 연산자
- 관계 연산자
- 논리 연산자
- instanceof
- assignment(=) operator
- 화살표(->) 연산자
- 3항 연산자
- 연산자 우선 순위
- (optional) Java 13. switch 연산자
## 마감일시
2022년 6월 16일 오후 10시

**Comment by euichaan** [comment]
https://chan9.tistory.com/187

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/3.%20%EC%97%B0%EC%82%B0%EC%9E%90.md

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-03

**Comment by ChooSeoyeon** [comment]
https://choo.oopy.io/387fdd1c-bb18-4500-99b4-b0e9c1924d79
