### ISSUE TITLE
6주차 과제: 상속

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#6]
# 목표
자바의 상속에 대해 학습하세요.

# 학습할 것 (필수)
- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
- 추상 클래스
- final 키워드
- Object 클래스
# 마감일시
2023년 7월 7일 오후 10시까지.

**Comment by euichaan** [comment]
https://chan9.tistory.com/191

**Comment by ssssujini99** [comment]
https://adhesive-honey-f62.notion.site/6-668149cbf57b4c2ba34e267f1ea3ef34?pvs=4

**Comment by ChooSeoyeon** [comment]
https://silent-apparatus-578.notion.site/c7a2166fce1340e8ac39004feb895c7c?pvs=4

다하진 못했습니다...

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/6.%20%EC%83%81%EC%86%8D.md
