### ISSUE TITLE
7주차 과제: 패키지

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#7]
# 목표
자바의 패키지에 대해 학습하세요.

# 학습할 것 (필수)
- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- -classpath 옵션
- 접근지시자
# 학습할 것 (선택)
- 불변
- static import
# 마감일시
2023년 7월 14일 오후 10시까지.

**Comment by euichaan** [comment]
https://humorous-bass-b9e.notion.site/d231b9f81c554933a4c8db48cbd95289?pvs=4

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/7.%20%ED%8C%A8%ED%82%A4%EC%A7%80.md
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/7.2%20classpath%EC%99%80%20modulepath.md

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-07
