### ISSUE TITLE
8주차 과제: 인터페이스

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#8]
# 목표
자바의 인터페이스에 대해 학습하세요.

# 학습할 것 (필수)
- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8
- 인터페이스의 static 메소드, 자바 8
- 인터페이스의 private 메소드, 자바 9
# 마감일시
2023년 7월 20일 목요일, 오후 10시까지

**Comment by euichaan** [comment]
https://humorous-bass-b9e.notion.site/ee3b0410cf0b4d90a723c9f3c2c9198e?pvs=4

**Comment by ssssujini99** [comment]
https://adhesive-honey-f62.notion.site/4bf681d42ec94847b05cd235e394f5b0?pvs=4

**Comment by binary-ho** [comment]
https://dwaejinho.tistory.com/entry/Interface

**Comment by ChooSeoyeon** [comment]
https://silent-apparatus-578.notion.site/c7a2166fce1340e8ac39004feb895c7c?pvs=4

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-08
