### ISSUE TITLE
9주차 과제: 예외 처리

### ISSUE THREAD

**Issue by euichaan** [java-live-study/live-study#9]
# 목표
자바의 예외 처리에 대해 학습하세요.

# 학습할 것 (필수)
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법
# 마감일시
2023년 7월 30일 오후 8시까지

**Comment by euichaan** [comment]
https://humorous-bass-b9e.notion.site/c0084b9ccf3c4db68b931a3c36feee40?pvs=4

**Comment by binary-ho** [comment]
https://github.com/binary-ho/TIL-public/blob/main/JAVA/%EB%B0%B1%EA%B8%B0%EC%84%A0%20%EB%9D%BC%EC%9D%B4%EB%B8%8C%20%EC%8A%A4%ED%84%B0%EB%94%94/9.%20%EC%9E%90%EB%B0%94%20%EC%98%88%EC%99%B8%20%EC%B2%98%EB%A6%AC.md

**Comment by ChooSeoyeon** [comment]
https://silent-apparatus-578.notion.site/929b9d0e770b4d8d8b1ddaa234b3a5d2?pvs=4

**Comment by uwoobeat** [comment]
https://uwoobeat.vercel.app/java-live-study-09
